# Site settings
title: Blogity blog blog. Journal
name: fragmede
email: blog@onepatchdown.net
description: "blogidy blog blog: random notes/thoughts/etc"
baseurl: ""
url: "http://blog.onepatchdown.net"
#twitter_username: 
github_username: fragmede

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
